# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1012, 612)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_model = QtWidgets.QPushButton(self.frame)
        self.btn_model.setMinimumSize(QtCore.QSize(80, 30))
        self.btn_model.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.btn_model.setFont(font)
        self.btn_model.setObjectName("btn_model")
        self.gridLayout.addWidget(self.btn_model, 0, 0, 1, 1)
        self.label_model = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_model.setFont(font)
        self.label_model.setObjectName("label_model")
        self.gridLayout.addWidget(self.label_model, 0, 1, 1, 1)
        self.btn_img = QtWidgets.QPushButton(self.frame)
        self.btn_img.setMinimumSize(QtCore.QSize(80, 30))
        self.btn_img.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.btn_img.setFont(font)
        self.btn_img.setObjectName("btn_img")
        self.gridLayout.addWidget(self.btn_img, 1, 0, 1, 1)
        self.label_img = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_img.setFont(font)
        self.label_img.setObjectName("label_img")
        self.gridLayout.addWidget(self.label_img, 1, 1, 1, 1)
        self.btn_begin = QtWidgets.QPushButton(self.frame)
        self.btn_begin.setMinimumSize(QtCore.QSize(80, 30))
        self.btn_begin.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.btn_begin.setFont(font)
        self.btn_begin.setObjectName("btn_begin")
        self.gridLayout.addWidget(self.btn_begin, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.label_in = QtWidgets.QLabel(self.centralwidget)
        self.label_in.setAutoFillBackground(True)
        self.label_in.setFrameShape(QtWidgets.QFrame.Box)
        self.label_in.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_in.setText("")
        self.label_in.setObjectName("label_in")
        self.verticalLayout.addWidget(self.label_in)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1012, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_model.setText(_translate("MainWindow", "选择模型"))
        self.label_model.setText(_translate("MainWindow", "None"))
        self.btn_img.setText(_translate("MainWindow", "输入图像"))
        self.label_img.setText(_translate("MainWindow", "None"))
        self.btn_begin.setText(_translate("MainWindow", "开始检测"))
